FIx: ATB and title for static page essays is buggy
suttacentral/suttacentral pull request #2315
Opened 2021-10-30 10:45 UTC by ihongda

2021-10-30 21:10 UTC, sujato requested changes
There are still some bugs.

*Running branch Hongda-work in Incognito, site language English, clear site data first*.

- Click on the three essays from the Home page, all works fine.
- The problem with missing titles is fixed (#2314)
- **But!** Once on an essay page, if I refresh, the incorrect ATB comes up (i.e. it has INTRODUCTION | DONATIONS etc.)
- The same thing happens if I am on another static page, eg. `/methodology`. The ATB is correct when I navigate there, but is incorrect after refresh.
- Testing in German: change site language to `de`, German essays don't appear at all, it's just in English.

2021-10-31 03:19 UTC, ihongda commented
>Testing in German: change site language to de, German essays don't appear at all, it's just in English.

Bhante, Where is the German version of essays?
It seems that there are only these three essays at the moment:
 
`http://localhost/discourses-guide-sujato`
`http://localhost/vinaya-guide-brahmali`
`http://localhost/abhidhamma-guide-sujato`

2021-10-31 03:47 UTC, ihongda commented
>Testing in German: change site language to de, German essays don't appear at all, it's just in English.

Since the localization method has been modified, some modifications need to be made to adapt, I will open another issue.

2021-10-31 20:22 UTC, sujato approved these changes

2021-11-01 01:44 UTC, merged